@urlBase = http://localhost:5000

GET {{urlBase}}/ventas/ HTTP/1.1
###

GET http://localhost:5000/ventas/6161966804aad3dd4c34c71c HTTP/1.1
###

POST http://localhost:5000/ventas HTTP/1.1
content-type: application/json

{
    "id": 102032,
    "total": 2345,
    "cantidad":1,
    "documento":123455,
    "cliente":"juan martibnex",
    "vendedor":"ricardo perea"
}
###

DELETE {{urlBase}}/students/6161966804aad3dd4c34c71c

###
PUT http://localhost:5000/ventas/6174e485390f3e33c48e8e55
content-type: application/json

{
    "id": 102032,
    "total": 2345,
    "cantidad":1,
    "documento":123455,
    "cliente":"juan martibnex",
    "vendedor":"ricardo perea"
}
